CREATE TABLE IF NOT EXISTS BRANDS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS PRICE_LISTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS PRICES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    BRAND_ID INT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(20, 3) NOT NULL,
    CURR CHAR(3) NOT NULL,
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
    FOREIGN KEY (PRICE_LIST) REFERENCES PRICE_LISTS(ID)
);

/* COVERING INDEX (USE IF TABLE IS READ-HEAVY) */
CREATE INDEX QUERY_PRICE_COVERING_INDEX ON PRICES (BRAND_ID, PRODUCT_ID, START_DATE, END_DATE, PRIORITY DESC, ID, PRICE, CURR, PRICE_LIST);

/* COMPOSITE INDEX (USE IF TABLE IS WRITE-HEAVY) */
/* CREATE INDEX QUERY_PRICE_COMPOSITE_INDEX ON PRICES (BRAND_ID, PRODUCT_ID, START_DATE, END_DATE, PRIORITY DESC); */
