version: 2

updates:

  # ================================
  # UPDATE GRADLE DEPENDENCIES
  # ================================
  - package-ecosystem: gradle
    directory: /
    schedule:
        interval: weekly

  # ================================
  # UPDATE GITHUB ACTIONS
  # ================================
  - package-ecosystem: github-actions
    directory: /
    schedule:
        interval: weekly
