
# Submit dependencies
name: Dependencies

on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  dependencies:

    name: Submit dependencies
    runs-on: ubuntu-latest

    steps:

    # ================================
    # SHALLOW CLONE
    # ================================
    - name: Shallow clone
      uses: actions/checkout@v5

    # ================================
    # SET UP JDK
    # ================================
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-package: jdk
        java-version: 24

    # ================================
    # SUBMIT DEPENDENCIES
    # ================================
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
      env:
        dependency-graph-exclude-projects: api-compatibility
        dependency-graph-exclude-configurations: '.*[Tt]est(Compile|Runtime)Classpath'
